// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classroom.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClassroom = `-- name: CreateClassroom :one
INSERT INTO public."classroom" (
    name, subject, section, description, code, room, card_background, illustration_index, teacher_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, subject, section, description, room, code, card_background, illustration_index, allow_users_to_comment, allow_users_to_post, teacher_id, created_at, updated_at
`

type CreateClassroomParams struct {
	Name              string      `json:"name"`
	Subject           pgtype.Text `json:"subject"`
	Section           string      `json:"section"`
	Description       pgtype.Text `json:"description"`
	Code              string      `json:"code"`
	Room              pgtype.Text `json:"room"`
	CardBackground    string      `json:"card_background"`
	IllustrationIndex int32       `json:"illustration_index"`
	TeacherID         string      `json:"teacher_id"`
}

func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, createClassroom,
		arg.Name,
		arg.Subject,
		arg.Section,
		arg.Description,
		arg.Code,
		arg.Room,
		arg.CardBackground,
		arg.IllustrationIndex,
		arg.TeacherID,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.Section,
		&i.Description,
		&i.Room,
		&i.Code,
		&i.CardBackground,
		&i.IllustrationIndex,
		&i.AllowUsersToComment,
		&i.AllowUsersToPost,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassroom = `-- name: GetClassroom :one
SELECT id, name, subject, section, description, room, code, card_background, illustration_index, allow_users_to_comment, allow_users_to_post, teacher_id, created_at, updated_at FROM public."classroom"
WHERE id = $1
`

func (q *Queries) GetClassroom(ctx context.Context, id pgtype.UUID) (Classroom, error) {
	row := q.db.QueryRow(ctx, getClassroom, id)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.Section,
		&i.Description,
		&i.Room,
		&i.Code,
		&i.CardBackground,
		&i.IllustrationIndex,
		&i.AllowUsersToComment,
		&i.AllowUsersToPost,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassroomByCode = `-- name: GetClassroomByCode :one
SELECT id, name, subject, section, description, room, code, card_background, illustration_index, allow_users_to_comment, allow_users_to_post, teacher_id, created_at, updated_at FROM public."classroom"
WHERE code = $1
`

func (q *Queries) GetClassroomByCode(ctx context.Context, code string) (Classroom, error) {
	row := q.db.QueryRow(ctx, getClassroomByCode, code)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subject,
		&i.Section,
		&i.Description,
		&i.Room,
		&i.Code,
		&i.CardBackground,
		&i.IllustrationIndex,
		&i.AllowUsersToComment,
		&i.AllowUsersToPost,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
