// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classroom_enrollment.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClassroomEnrollment = `-- name: CreateClassroomEnrollment :one
INSERT INTO public."classroom_enrollment" (
    classroom_id, user_id
) VALUES (
    $1, $2
)
RETURNING id, classroom_id, user_id, created_at
`

type CreateClassroomEnrollmentParams struct {
	ClassroomID pgtype.UUID `json:"classroom_id"`
	UserID      string      `json:"user_id"`
}

func (q *Queries) CreateClassroomEnrollment(ctx context.Context, arg CreateClassroomEnrollmentParams) (ClassroomEnrollment, error) {
	row := q.db.QueryRow(ctx, createClassroomEnrollment, arg.ClassroomID, arg.UserID)
	var i ClassroomEnrollment
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getClassroomEnrollment = `-- name: GetClassroomEnrollment :one
SELECT id, classroom_id, user_id, created_at FROM public."classroom_enrollment"
WHERE id = $1
`

func (q *Queries) GetClassroomEnrollment(ctx context.Context, id pgtype.UUID) (ClassroomEnrollment, error) {
	row := q.db.QueryRow(ctx, getClassroomEnrollment, id)
	var i ClassroomEnrollment
	err := row.Scan(
		&i.ID,
		&i.ClassroomID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
