// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           pgtype.Text      `json:"access_token"`
	RefreshToken          pgtype.Text      `json:"refresh_token"`
	IDToken               pgtype.Text      `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Classroom struct {
	ID                  pgtype.UUID      `json:"id"`
	Name                string           `json:"name"`
	Subject             pgtype.Text      `json:"subject"`
	Section             string           `json:"section"`
	Description         pgtype.Text      `json:"description"`
	Room                pgtype.Text      `json:"room"`
	Code                string           `json:"code"`
	CardBackground      string           `json:"card_background"`
	IllustrationIndex   int32            `json:"illustration_index"`
	AllowUsersToComment bool             `json:"allow_users_to_comment"`
	AllowUsersToPost    bool             `json:"allow_users_to_post"`
	TeacherID           string           `json:"teacher_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type ClassroomEnrollment struct {
	ID          pgtype.UUID      `json:"id"`
	ClassroomID pgtype.UUID      `json:"classroom_id"`
	UserID      string           `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ClassroomMessage struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      string           `json:"user_id"`
	ClassroomID pgtype.UUID      `json:"classroom_id"`
	Message     pgtype.Text      `json:"message"`
	Attachments []string         `json:"attachments"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ClassroomTopic struct {
	ID          pgtype.UUID      `json:"id"`
	ClassroomID pgtype.UUID      `json:"classroom_id"`
	Name        string           `json:"name"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Jwk struct {
	ID         string           `json:"id"`
	PublicKey  string           `json:"public_key"`
	PrivateKey string           `json:"private_key"`
	Alg        pgtype.Text      `json:"alg"`
	Crv        pgtype.Text      `json:"crv"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

type Note struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      string           `json:"user_id"`
	Title       pgtype.Text      `json:"title"`
	Content     pgtype.Text      `json:"content"`
	Attachments []string         `json:"attachments"`
	IsPinned    bool             `json:"is_pinned"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Notification struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     string           `json:"user_id"`
	ActorID    pgtype.Text      `json:"actor_id"`
	Type       interface{}      `json:"type"`
	ResourceID string           `json:"resource_id"`
	IsRead     bool             `json:"is_read"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID        string           `json:"id"`
	Token     string           `json:"token"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	UserID    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Stream struct {
	ID                           pgtype.UUID      `json:"id"`
	ClassroomID                  pgtype.UUID      `json:"classroom_id"`
	UserID                       string           `json:"user_id"`
	ClassroomTopicID             pgtype.UUID      `json:"classroom_topic_id"`
	Type                         interface{}      `json:"type"`
	Title                        pgtype.Text      `json:"title"`
	Content                      pgtype.Text      `json:"content"`
	Attachments                  []string         `json:"attachments"`
	Links                        []string         `json:"links"`
	Points                       pgtype.Int4      `json:"points"`
	IsPinned                     bool             `json:"is_pinned"`
	AcceptingSubmissions         bool             `json:"accepting_submissions"`
	CloseSubmissionsAfterDueDate bool             `json:"close_submissions_after_due_date"`
	AnnounceTo                   []string         `json:"announce_to"`
	AnnounceToAll                bool             `json:"announce_to_all"`
	DueAt                        pgtype.Timestamp `json:"due_at"`
	ScheduledAt                  pgtype.Timestamp `json:"scheduled_at"`
	CreatedAt                    pgtype.Timestamp `json:"created_at"`
	UpdatedAt                    pgtype.Timestamp `json:"updated_at"`
}

type StreamComment struct {
	ID          pgtype.UUID      `json:"id"`
	StreamID    pgtype.UUID      `json:"stream_id"`
	ClassroomID pgtype.UUID      `json:"classroom_id"`
	UserID      string           `json:"user_id"`
	Content     pgtype.Text      `json:"content"`
	Attachment  pgtype.Text      `json:"attachment"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Submission struct {
	ID          pgtype.UUID      `json:"id"`
	StreamID    pgtype.UUID      `json:"stream_id"`
	ClassroomID pgtype.UUID      `json:"classroom_id"`
	UserID      string           `json:"user_id"`
	Attachments []string         `json:"attachments"`
	Links       []string         `json:"links"`
	Content     pgtype.Text      `json:"content"`
	Grade       pgtype.Int4      `json:"grade"`
	IsTurnedIn  bool             `json:"is_turned_in"`
	IsGraded    bool             `json:"is_graded"`
	IsReturned  bool             `json:"is_returned"`
	SubmittedAt pgtype.Timestamp `json:"submitted_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type SubmissionComment struct {
	ID           pgtype.UUID      `json:"id"`
	SubmissionID pgtype.UUID      `json:"submission_id"`
	UserID       string           `json:"user_id"`
	Content      pgtype.Text      `json:"content"`
	Attachment   pgtype.Text      `json:"attachment"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"email_verified"`
	Image         pgtype.Text      `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
