// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
