// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateClassroom(ctx context.Context, arg CreateClassroomParams) (Classroom, error)
	CreateClassroomEnrollment(ctx context.Context, arg CreateClassroomEnrollmentParams) (ClassroomEnrollment, error)
	GetClassroom(ctx context.Context, id pgtype.UUID) (Classroom, error)
	GetClassroomByCode(ctx context.Context, code string) (Classroom, error)
	GetClassroomEnrollment(ctx context.Context, id pgtype.UUID) (ClassroomEnrollment, error)
	GetUser(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
